# This workflow will build the Angular app and deploy the build artifacts to the gh-pages branch.

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: write
  pages: write

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    # Checkout the main branch
    - uses: actions/checkout@v4
      with:
        ref: 'main'

    # Set up Node.js
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Install dependencies
    - run: npm ci

    # Build the Angular app
    - name: Build Angular App
      run: npm run deploy --if-present

    # Upload build artifacts
    - name: Upload Build Artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        name: github-pages
        path: dist/plane-alert/browser/

    # Deploy to GitHub Pages using actions/deploy-pages
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4